#Generated by VisualGDB (http://visualgdb.com)
#DO NOT EDIT THIS FILE MANUALLY UNLESS YOU ABSOLUTELY NEED TO
#USE VISUALGDB PROJECT PROPERTIES DIALOG INSTEAD

BINARYDIR := Debug

#Toolchain
CC := gcc
CXX := g++
LD := $(CXX)
AR := ar
OBJCOPY := objcopy

#Additional flags
PREPROCESSOR_MACROS := DEBUG _DEBUG
INCLUDE_DIRS := /home/yyz/C/Bex/boost/include /home/yyz/C/Bex/Bex/src ../../test/main
LIBRARY_DIRS := /home/yyz/C/Bex/boost/lib
LIBRARY_NAMES := pthread
ADDITIONAL_LINKER_INPUTS := /home/yyz/C/Bex/boost/lib/libboost_system.a /home/yyz/C/Bex/boost/lib/libboost_unit_test_framework.a /home/yyz/C/Bex/boost/lib/libboost_thread.a /home/yyz/C/Bex/boost/lib/libboost_locale.a
MACOS_FRAMEWORKS := 

CFLAGS := -ggdb -ffunction-sections -O0
CXXFLAGS := -ggdb -ffunction-sections -O0 -std=c++11
ASFLAGS := 
LDFLAGS := -Wl,-gc-sections
COMMONFLAGS := 

START_GROUP := -Wl,--start-group
END_GROUP := -Wl,--end-group

#Additional options detected from testing the toolchain
IS_LINUX_PROJECT := 1
